version: "3.3"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports: 
      - '3000:3000'
    volumes: 
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on: 
      - backend

